In [2]:
import pandas as pd
df = pd.read_csv("subbyte.csv")
df

0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15
0   63  7c  77  7b  f2  6b  6f  c5  30   1  67  2b  fe  d7  ab  76
1   ca  82  c9  7d  fa  59  47  f0  ad  d4  a2  af  9c  a4  72  c0
2   b7  fd  93  26  36  3f  f7  cc  34  a5  e5  f1  71  d8  31  15
3    4  c7  23  c3  18  96   5  9a   7  12  80  e2  eb  27  b2  75
4    9  83  2c  1a  1b  6e  5a  a0  52  3b  d6  b3  29  e3  2f  84
5   53  d1   0  ed  20  fc  b1  5b  6a  cb  be  39  4a  4c  58  cf
6   d0  ef  aa  fb  43  4d  33  85  45  f9   2  7f  50  3c  9f  a8
7   51  a3  40  8f  92  9d  38  f5  bc  b6  da  21  10  ff  f3  d2
8   cd  0c  13  ec  5f  97  44  17  c4  a7  7e  3d  64  5d  19  73
9   60  81  4f  dc  22  2a  90  88  46  ee  b8  14  de  5e  0b  db
10  e0  32  3a  0a  49   6  24  5c  c2  d3  ac  62  91  95  e4  79
11  e7  c8  37  6d  8d  d5  4e  a9  6c  56  f4  ea  65  7a  ae   8
12  ba  78  25  2e  1c  a6  b4  c6  e8  dd  74  1f  4b  bd  8b  8a
13  70  3e  b5  66  48   3  f6  0e  61  35  57  b9  86  c1  1d  9e
14  e1  f8  98  11  69  d9  8e  94  9b  1e  87  e9  ce  55  28  df
15  8c  a1  89  0d  bf  e6  42  68  41  99  2d  0f  b0  54  bb  16

In [3]:
t="""63  7c  77  7b  f2  6b  6f  c5  30   1  67  2b  fe  d7  ab  76
ca  82  c9  7d  fa  59  47  f0  ad  d4  a2  af  9c  a4  72  c0
b7  fd  93  26  36  3f  f7  cc  34  a5  e5  f1  71  d8  31  15
 4  c7  23  c3  18  96   5  9a   7  12  80  e2  eb  27  b2  75
 9  83  2c  1a  1b  6e  5a  a0  52  3b  d6  b3  29  e3  2f  84
53  d1   0  ed  20  fc  b1  5b  6a  cb  be  39  4a  4c  58  cf
d0  ef  aa  fb  43  4d  33  85  45  f9   2  7f  50  3c  9f  a8
51  a3  40  8f  92  9d  38  f5  bc  b6  da  21  10  ff  f3  d2
cd  0c  13  ec  5f  97  44  17  c4  a7  7e  3d  64  5d  19  73
60  81  4f  dc  22  2a  90  88  46  ee  b8  14  de  5e  0b  db
e0  32  3a  0a  49   6  24  5c  c2  d3  ac  62  91  95  e4  79
e7  c8  37  6d  8d  d5  4e  a9  6c  56  f4  ea  65  7a  ae   8
ba  78  25  2e  1c  a6  b4  c6  e8  dd  74  1f  4b  bd  8b  8a
70  3e  b5  66  48   3  f6  0e  61  35  57  b9  86  c1  1d  9e
e1  f8  98  11  69  d9  8e  94  9b  1e  87  e9  ce  55  28  df
8c  a1  89  0d  bf  e6  42  68  41  99  2d  0f  b0  54  bb  16"""
import numpy as np
r=t.split('\n')
submat=[]
for i in r:
    tr=i.split()
    for j in range(len(tr)):
        tr[j]=int(tr[j],16)
    submat.append(tr)
submat=np.array(submat)
submat

array([[ 99, 124, 119, 123, 242, 107, 111, 197,  48,   1, 103,  43, 254,
        215, 171, 118],
       [202, 130, 201, 125, 250,  89,  71, 240, 173, 212, 162, 175, 156,
        164, 114, 192],
       [183, 253, 147,  38,  54,  63, 247, 204,  52, 165, 229, 241, 113,
        216,  49,  21],
       [  4, 199,  35, 195,  24, 150,   5, 154,   7,  18, 128, 226, 235,
         39, 178, 117],
       [  9, 131,  44,  26,  27, 110,  90, 160,  82,  59, 214, 179,  41,
        227,  47, 132],
       [ 83, 209,   0, 237,  32, 252, 177,  91, 106, 203, 190,  57,  74,
         76,  88, 207],
       [208, 239, 170, 251,  67,  77,  51, 133,  69, 249,   2, 127,  80,
         60, 159, 168],
       [ 81, 163,  64, 143, 146, 157,  56, 245, 188, 182, 218,  33,  16,
        255, 243, 210],
       [205,  12,  19, 236,  95, 151,  68,  23, 196, 167, 126,  61, 100,
         93,  25, 115],
       [ 96, 129,  79, 220,  34,  42, 144, 136,  70, 238, 184,  20, 222,
         94,  11, 219],
       [224,  50,  58,  10,  7

In [4]:
from numba import njit
from numba import jit
from numba import vectorize
from numba import prange

In [5]:
import time
import numpy as np

In [6]:
@njit()
def read_subbyte(num):
    
    i = num//16
    j = num%16
    num =submat[i][j]
    return num
npread_subbyte=np.frompyfunc(read_subbyte,1,1)


In [7]:
import numpy as np

key = 'HARISHBHARADWAJ1'

t = np.empty([4, 4], dtype=int)

l=0

for i in range(4):
    for j in range(4):
        t[i][j] = ord(key[l])
        l+=1
        
t[0].shape



(4,)

In [8]:
# print(t[-1][1:])
# print(t[-1][0])
# temp1=t[-1][1:]+[t[-1][0]]
# temp1 = np.append(t[-1][1:], t[-1][0])
temp1 = np.roll(t[-1], -1)
print(temp1)

[65 74 49 87]


In [9]:
temp = []
for i in temp1:
    temp.append(npread_subbyte(i))
    
temp = np.array(temp)
temp

array([131, 214, 199,  91])

In [10]:
def GenerateKeys(t,rcon,temp):
    o=[]
    for i in range(4):
        p=t[i].T^rcon^temp
        o.append(p)
        temp = p
    return o

In [11]:
# rcon = [1,2,4,8,16,32,64,128,27,54]

rcon=[[1,0,0,0],
      [2,0,0,0],
      [4,0,0,0],
      [8,0,0,0],
      [10,0,0,0],
      [0x20,0,0,0],
      [0x40,0,0,0],
      [0x80,0,0,0],
      [0x1b,0,0,0],
      [0x36,0,0,0]
     ]
rcon=np.array(rcon)

In [12]:
keys = []
keys.append(t)
keys = np.array(keys)
# keys
for i in range(10):
    t = GenerateKeys(t, rcon[i], temp)
    t = np.array(t)
    keys = np.append(keys, t)
    temp1 = np.roll(t[-1], -1)
    temp = []
    #print(temp1)
    
    for j in temp1:
        temp.append(read_subbyte(j))
#     print(temp)
#     print(t)

keys = np.array(keys)
keys = np.reshape(keys, (-1,16))
    
keys

array([[ 72,  65,  82,  73,  83,  72,  66,  72,  65,  82,  65,  68,  87,
         65,  74,  49],
       [202, 151, 149,  18, 152, 223, 215,  90, 216, 141, 150,  30, 142,
        204, 220,  47],
       [131,  17, 128,  11,  25, 206,  87,  81, 195,  67, 193,  79,  79,
        143,  29,  96],
       [244, 181,  80, 143, 233, 123,   7, 222,  46,  56, 198, 145, 101,
        183, 219, 241],
       [ 85,  12, 241, 194, 180, 119, 246,  28, 146,  79,  48, 141, 255,
        248, 235, 124],
       [ 30, 229, 225, 212, 160, 146,  23, 200,  56, 221,  39,  69, 205,
         37, 204,  57],
       [  1, 174, 243, 105, 129,  60, 228, 161, 153, 225, 195, 228, 116,
        196,  15, 221],
       [ 93, 216,  50, 251, 156, 228, 214,  90,  69,   5,  21, 190, 113,
        193,  26,  99],
       [165, 122, 201,  88, 185, 158,  31,   2, 124, 155,  10, 188, 141,
         90,  16, 223],
       [  0, 176,  87,   5, 162,  46,  72,   7, 197, 181,  66, 187,  83,
        239,  82, 100],
       [233, 176,  20, 232, 12

In [13]:
new_keys = []
for i in range(len(keys)):
    temp_key = np.matrix(keys[i],dtype=np.int32).reshape(4,4)
    new_keys.append(temp_key)
keys = np.array(new_keys,dtype=np.int32)

In [14]:
for i in range(len(keys)):
    keys[i] = keys[i].transpose()
    
keys

array([[[ 72,  83,  65,  87],
        [ 65,  72,  82,  65],
        [ 82,  66,  65,  74],
        [ 73,  72,  68,  49]],

       [[202, 152, 216, 142],
        [151, 223, 141, 204],
        [149, 215, 150, 220],
        [ 18,  90,  30,  47]],

       [[131,  25, 195,  79],
        [ 17, 206,  67, 143],
        [128,  87, 193,  29],
        [ 11,  81,  79,  96]],

       [[244, 233,  46, 101],
        [181, 123,  56, 183],
        [ 80,   7, 198, 219],
        [143, 222, 145, 241]],

       [[ 85, 180, 146, 255],
        [ 12, 119,  79, 248],
        [241, 246,  48, 235],
        [194,  28, 141, 124]],

       [[ 30, 160,  56, 205],
        [229, 146, 221,  37],
        [225,  23,  39, 204],
        [212, 200,  69,  57]],

       [[  1, 129, 153, 116],
        [174,  60, 225, 196],
        [243, 228, 195,  15],
        [105, 161, 228, 221]],

       [[ 93, 156,  69, 113],
        [216, 228,   5, 193],
        [ 50, 214,  21,  26],
        [251,  90, 190,  99]],

       [[165, 185, 124, 

In [15]:
pre_mat=np.array([[2,3,1,1],[1,2,3,1],[1,1,2,3],[3,1,1,2]])

In [16]:
@njit()
def galoisMult(a, b):
    p = 0
    hiBitSet = 0
    for i in range(8):
        if b & 1 == 1:
            p ^= a
        hiBitSet = a & 0x80
        a <<= 1
        if hiBitSet == 0x80:
            a ^= 0x1b
        b >>= 1
    return p % 128
galoisMult(2,255)
npgaloisMult = np.frompyfunc(galoisMult, 2, 1)

In [17]:
# @jit(nopython=False)
# @vectorize(["int32(int32)"])
# @njit(parallel=True)
def shift_rows(res):
    for i in range(1,res.shape[0]):
        res[i:i+1]=np.roll(res[i:i+1],-i,axis=1)
    return res.astype('int32')

In [18]:
# @jit(nopython=False)
@vectorize(["int32(int32, int32)"])
def add_rnd_keys(x,y):
    return x^y

# @jit(nopython=False)
# @vectorize(["int32(int32, int32)"])
def custom_multiply(x, y):
    return np.array([np.bitwise_xor.reduce(npgaloisMult(row,column)) for row in x for column in y.T]).reshape(x.shape[0], y.shape[1])

# @jit(nopython=True)
def npmix_col(res):
    return custom_multiply(pre_mat,res)

In [19]:
msg="hi this msg is encrypted good luck with this bye"
msgar=[]
ms=[]
for i in range(0,len(msg),4):
    l=[]
    for j in range(4):
        if i+j<len(msg):
            l.append(ord(msg[i+j]))
    ms.append(l)
    if len(ms)==4:
        if len(ms[-1])!=4:
            ms[-1]+=[0]*(4-len(ms[-1]))
        msgar.append(np.array(ms,dtype=np.int32))
        ms=[]
msgar=np.array(msgar,dtype=np.int32)
for i in range(len(msgar)):
    msgar[i]=msgar[i].T
add_rnd_keys(keys[0],msgar[0])

array([[ 32,  59,  44,  62],
       [ 40,  33,  33,  50],
       [114,  49,  38, 106],
       [ 61, 104, 100,  84]])

In [20]:
rest=[]
def enc():
    global rest
    for mat in range(len(msgar)):
        res=msgar[mat]
        for rnd in range(11):
            if rnd==0:
                res=add_rnd_keys(keys[rnd],res)
            elif rnd<10:
                res=add_rnd_keys(keys[rnd],npmix_col(shift_rows(npread_subbyte(res))))
            else:
                res=add_rnd_keys(keys[rnd],shift_rows(npread_subbyte(res)))
        rest.append(res)
start = time.time()
enc()
end = time.time()
print("Elapsed (after compilation) = %s" % (end - start))
for i in rest:
    print(i)

Elapsed (after compilation) = 0.002991199493408203
[[197 137 179 184]
 [102 202 100  72]
 [ 20  59 212  48]
 [114  75 173 241]]
[[163   9 234 136]
 [ 47  57  66 218]
 [ 34  35 117 122]
 [ 23 107  12  82]]
[[ 63   4  81  65]
 [234 188 111  34]
 [151 109  30   0]
 [ 19  36 241 128]]
